spring.application.name=HomeTreasury
pluggy.client-id=${PLUGGY_CLIENT_ID}
pluggy.client-secret=${PLUGGY_CLIENT_SECRET}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=${JWT_SECRET}
jwt.expiration-ms=${JWT_EXPIRATION_MS}

app.cors.allowed-origins=http://localhost:5173